version: "3"
services:
  db:
    image: postgres
    container_name: db
    env_file:
      - db.env
    networks:
      - short-back

  api:
    build: .
    container_name: api
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
    command: ["./init.sh"]
    networks:
      - short-back

networks:
  short-back:
    driver: bridge
